---
title: "Online shoppers dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: scroll
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
library(scales)
library(randomForest)
library(umap)
library(reticulate)
```

```{r setup_df, include=FALSE}
df <- read.csv("online_shoppers_intention.csv")
    df$OperatingSystems <- factor(df$OperatingSystems)
    df$Browser <- factor(df$Browser)
    df$Region <- factor(df$Region)
    df$TrafficType <- factor(df$TrafficType)
    df$VisitorType <- factor(df$VisitorType)
    df$Month <- factor(df$Month, levels = c("Feb", "Mar", "May", "June", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"))
mycols <- c("#CD534CFF", "#EFC000FF","#0073C2FF", "#868686FF")

months <- nrow(df %>% group_by(Month)%>% tally())
```

```{r calculate_prox, include=FALSE}
sample_df <- df %>%
  group_by(Revenue) %>%
  sample_frac(0.2) %>%
  ungroup

set.seed(42)
rf <- randomForest(x = sample_df[,1:17], y = factor(sample_df$Revenue), ntree = 100, proximity = T, 
                   importance = TRUE, do.trace = 100)
prox <- rf$proximity
```


Inputs {.sidebar}
-------------------------------------

```{r inputs}
# shiny inputs defined here

selectInput("website", "Website:", 
                          choices=c("Administrative", "Informational", "ProductRelated"))

selectInput("month", 
            "Month:", 
            choices=c("Feb", "Mar", "May", "June", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")
            )

sliderInput("n_neighbours", "Num of neighbours",min = 3, max = 50, step = 1, value = 15)
sliderInput("min_dist", "Minimum distance",min = 0.01, max = 0.5, step = 0.01, value = 0.2)

```

Row
-----------------------------------------------------------------------

### Total Revenues

```{r}
renderValueBox({
  avgRevenue <- nrow(df %>% filter(Revenue == TRUE)) / months
  
 revenue <- nrow(df %>% filter(Revenue == TRUE & Month == input$month)) 
  
  valueBox(revenue, caption = 'Total Revenues', icon = "fa-shopping-cart",
           color=ifelse(revenue>=avgRevenue, "success", "warning"))  
})

```

### Total visitors 

```{r}
renderValueBox({
  avgVisitors <- nrow(df) / months
  visitors <- nrow(df %>% filter(Month == input$month)) 
  
  valueBox(visitors, caption='Total visitors', icon = "fa-users",
           color=ifelse(visitors>=avgVisitors, "success", "warning"))
})
```

### Average traffic 

```{r}
renderValueBox({
  traffic <- df %>% 
    filter(Month == input$month) %>%
    group_by(TrafficType) %>%
    summarise(n = n()) %>%
    arrange(desc(n)) %>%
    select(TrafficType) %>%
    slice(1)
    
  valueBox(traffic, caption='Average traffic type', icon = "fa-bus")
})
```


Column {.tabset}
-----------------------------------------------------------------------

### New Visitor

```{r new_visitor}

df %>%
  filter(VisitorType == "New_Visitor") %>%
  group_by(Revenue) %>%
  summarise(n = n()) %>%
  mutate(count = sum(n)) %>%
  mutate(freq = n/count) %>%
  ggplot( aes(x = "", y = freq, fill=Revenue)) +
  geom_bar(width = 1, size=1, stat = "identity", color="white") +
  coord_polar("y", start = 0) +
  geom_text(aes(label=percent(freq)), position = position_stack(vjust=0.5), color="white") +
  scale_fill_manual(values = mycols) +
  theme_void()  

```

### Returning Visitor

```{r returning_visitor}

df %>%
  filter(VisitorType == "Returning_Visitor") %>%
  group_by(Revenue) %>%
  summarise(n = n()) %>%
  mutate(count = sum(n)) %>%
  mutate(freq = n/count) %>%
  ggplot( aes(x = "", y = freq, fill=Revenue)) +
  geom_bar(width = 1, size=1, stat = "identity", color="white") +
  coord_polar("y", start = 0) +
  geom_text(aes(label=percent(freq)), position = position_stack(vjust=0.5), color="white") +
  scale_fill_manual(values = mycols) +
  theme_void()  

```

### Other

```{r other}

df %>%
  filter(VisitorType == "Other") %>%
  group_by(Revenue) %>%
  summarise(n = n()) %>%
  mutate(count = sum(n)) %>%
  mutate(freq = n/count) %>%
  ggplot( aes(x = "", y = freq, fill=Revenue)) +
  geom_bar(width = 1, size=1, stat = "identity", color="white") +
  coord_polar("y", start = 0) +
  geom_text(aes(label=percent(freq)), position = position_stack(vjust=0.5), color="white") +
  scale_fill_manual(values = mycols) +
  theme_void() 

```

### Total

```{r total}
renderPlot({
df %>%
    filter(Month == input$month) %>%
    group_by(VisitorType) %>%
    summarise(n = n()) %>%
    mutate(count = sum(n)) %>%
    mutate(freq = n/count) %>%
  ggplot( aes(x = "", y = freq, fill = VisitorType)) +
  geom_bar(width = 1, stat = "identity", color = "white") +
  coord_polar("y", start = 0) +
  geom_text(aes(label=percent(freq)), position = position_stack(vjust=0.5), color="white") +
  scale_fill_manual(values = mycols) +
  theme_void() 
})
```

Column { .tabset data-width=450}
-------------------------------------------------------------------

### UMAP
```{r}

renderPlot({
  dist <- 1/(1+prox)
  umap.res <- umap(dist, method = "umap-learn", n_components=2, metric="precomputed", transform_seed=42, 
                   n_neighbors=input$n_neighbours, min_dist=input$min_dist)
  embedding <- umap.res$layout
  
  embedding_df <- data.frame(embedding)
  embedding_df$class <- sample_df$Revenue
  
  embedding_df %>%
    ggplot(mapping = aes(x = embedding_df[,1], y = embedding_df[,2], color = class)) + 
    geom_point(alpha=.5, size=3) +
    labs(x="UMAP1", y="UMAP2") +
    scale_color_manual(values = mycols) +
    theme_light() 
})

```


### Density of Revenue per type of website

```{r}

renderPlot({
        df %>%
            filter(Month == input$month) %>%
            filter_(paste(input$website,">",0)) %>%
            ggplot(mapping = aes_string(x = input$website, fill = "Revenue", color = "Revenue")) + 
            geom_density(alpha=.5) +
            ggtitle(paste("Density of revenue on", input$website, "pages")) +
            scale_fill_manual(values = mycols) + 
            theme_light()
    })

```

### Revenue distribution per month

```{r}

renderPlot({
        df %>%
            filter(Month == input$month) %>%
            group_by(Revenue) %>%
            summarise(n = n()) %>%
            mutate(freq = n / sum(n)) %>%
            ggplot(aes(x="", y=freq, fill=Revenue)) +
            geom_bar(width = 1, size = 1, stat = "identity", color="white") +
            coord_polar(theta="y", start=0) +
            geom_text(aes(label=percent(freq)), position = position_stack(vjust=0.5), color="white") +
            scale_fill_manual(values = mycols) +
            theme_void() 
      
    })

```

